version: "3"
services:
  node-express-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/usr/app
    container_name: node-express-docker
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: npm start
